PRODUCTS = [
    # Apple
    {"name": "Apple iPhone"},
    {"name": "Apple MacBook"},
    {"name": "Apple Mac mini"},
    {"name": "Apple iPad"},
    {"name": "Apple Watch"},
    {"name": "Apple AirPods"},
    
    # Samsung
    {"name": "Samsung Galaxy"},
    {"name": "Samsung TV"},
    {"name": "Samsung Galaxy Tab"},
    {"name": "Samsung Galaxy Watch"},
    
    # Google
    {"name": "Google Pixel"},
    {"name": "Google Nest"},
    
    # Sony
    {"name": "Sony TV"},
    {"name": "Sony PlayStation"},
    {"name": "Sony headphones"},
    
    # Microsoft
    {"name": "Microsoft Surface"},
    {"name": "Xbox"},
    
    # Autres
    {"name": "Dell XPS"},
    {"name": "Lenovo ThinkPad"},
    {"name": "HP Spectre"},
    {"name": "Asus ROG"},
]
